<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.02" os="Windows 8" host="WINPD185161-734"><DocLocation><![CDATA[C:\LoyaltyProAutomationFrameWork\TestScripts\MasterDriverScript]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[MasterDriverScript]]></DName>
<Res><![CDATA[Res94]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[17-12-2020 - 22:55:34]]></Time>
<TimeTick>1608225934</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",3]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",3]]></Details>
<Time><![CDATA[17-12-2020 - 22:55:34]]></Time>
<TimeTick>1608225934</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[Run "iexplore.exe",3]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[17-12-2020 - 22:55:41]]></Time>
<TimeTick>1608225941</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Run "iexplore.exe",3]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore.exe",3]]></Details>
<Time><![CDATA[17-12-2020 - 22:55:41]]></Time>
<TimeTick>1608225941</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="15" status="Passed" >
<Disp><![CDATA[Run "iexplore.exe",3]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="14" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ HQ.Net | Login ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:55:49]]></Time>
<TimeTick>1608225949</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="16" >
<Disp><![CDATA[[ HQ.Net | Login ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ username ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:55:52]]></Time>
<TimeTick>1608225952</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="18" >
<Disp><![CDATA[[ username ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ username ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["105435"]]></Details>
<Time><![CDATA[17-12-2020 - 22:55:53]]></Time>
<TimeTick>1608225953</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="21" >
<Disp><![CDATA[[ username ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ password ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:55:56]]></Time>
<TimeTick>1608225956</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="23" >
<Disp><![CDATA[[ password ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ password ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Abcd1234"]]></Details>
<Time><![CDATA[17-12-2020 - 22:55:57]]></Time>
<TimeTick>1608225957</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="26" >
<Disp><![CDATA[[ password ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ Login ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:55:59]]></Time>
<TimeTick>1608225959</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="28" >
<Disp><![CDATA[[ Login ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ Login ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17-12-2020 - 22:56:00]]></Time>
<TimeTick>1608225960</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="31" >
<Disp><![CDATA[[ Login ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[OBrwsr_HQNetMainMenu]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[17-12-2020 - 22:56:31]]></Time>
<TimeTick>1608225991</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[OPge_HQNetMainMenu]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[17-12-2020 - 22:56:31]]></Time>
<TimeTick>1608225991</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[OWEdt_ModuleSearch.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:56:31]]></Time>
<TimeTick>1608225991</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="35" >
<Disp><![CDATA[OWEdt_ModuleSearch.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[OWEdt_ModuleSearch.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[17-12-2020 - 22:56:32]]></Time>
<TimeTick>1608225992</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="38" >
<Disp><![CDATA[OWEdt_ModuleSearch.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[OWEdt_ModuleSearch.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:56:32]]></Time>
<TimeTick>1608225992</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="40" >
<Disp><![CDATA[OWEdt_ModuleSearch.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[OWEdt_ModuleSearch.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Supplier Maintenance"]]></Details>
<Time><![CDATA[17-12-2020 - 22:56:33]]></Time>
<TimeTick>1608225993</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="43" >
<Disp><![CDATA[OWEdt_ModuleSearch.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[OWBtn_Go.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:56:33]]></Time>
<TimeTick>1608225993</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="45" >
<Disp><![CDATA[OWBtn_Go.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[OWBtn_Go.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17-12-2020 - 22:56:34]]></Time>
<TimeTick>1608225994</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="48" >
<Disp><![CDATA[OWBtn_Go.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[OFr_CFrame]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[17-12-2020 - 22:56:36]]></Time>
<TimeTick>1608225996</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[OWElm_SupplierMaintenance.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:56:36]]></Time>
<TimeTick>1608225996</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="51" >
<Disp><![CDATA[OWElm_SupplierMaintenance.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[OWElm_SupplierMaintenance.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17-12-2020 - 22:56:37]]></Time>
<TimeTick>1608225997</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="54" >
<Disp><![CDATA[OWElm_SupplierMaintenance.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ Supplier Maintenance ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:56:40]]></Time>
<TimeTick>1608226000</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="55" >
<Disp><![CDATA[[ Supplier Maintenance ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ WebButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[17-12-2020 - 22:56:46]]></Time>
<TimeTick>1608226006</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="61" >
<Disp><![CDATA[[ WebButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="50" >
<Disp><![CDATA[OFr_CFrame]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="34" >
<Disp><![CDATA[OPge_HQNetMainMenu]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="33" >
<Disp><![CDATA[OBrwsr_HQNetMainMenu]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[OBrwsr_SupplierMaintenance]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[17-12-2020 - 22:56:49]]></Time>
<TimeTick>1608226009</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[OPge_SupplierMaintenance]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[17-12-2020 - 22:56:49]]></Time>
<TimeTick>1608226009</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[OPge_SupplierMaintenance.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:56:49]]></Time>
<TimeTick>1608226009</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="65" >
<Disp><![CDATA[OPge_SupplierMaintenance.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[OFr_toolframe]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[17-12-2020 - 22:56:49]]></Time>
<TimeTick>1608226009</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[OWElm_CreateNewSupplier.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:56:49]]></Time>
<TimeTick>1608226009</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="69" >
<Disp><![CDATA[OWElm_CreateNewSupplier.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[[ Back ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:56:49]]></Time>
<TimeTick>1608226009</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="71" >
<Disp><![CDATA[[ Back ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[[ Back ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17-12-2020 - 22:56:51]]></Time>
<TimeTick>1608226011</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="74" >
<Disp><![CDATA[[ Back ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[[ Supplier Maintenance ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:56:54]]></Time>
<TimeTick>1608226014</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="76" >
<Disp><![CDATA[[ Supplier Maintenance ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ New Supplier - Wizard ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:56:58]]></Time>
<TimeTick>1608226018</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="78" >
<Disp><![CDATA[[ New Supplier - Wizard ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[[ Supplier Name ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:56:58]]></Time>
<TimeTick>1608226018</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="81" >
<Disp><![CDATA[[ Supplier Name ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[[ Supplier Maintenance ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:56:58]]></Time>
<TimeTick>1608226018</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="82" >
<Disp><![CDATA[[ Supplier Maintenance ].Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="68" >
<Disp><![CDATA[OFr_toolframe]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="64" >
<Disp><![CDATA[OPge_SupplierMaintenance]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[OWin_NewSupplier_Wizard]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:11]]></Time>
<TimeTick>1608226031</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Script Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:11]]></Time>
<TimeTick>1608226031</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Script Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:11]]></Time>
<TimeTick>1608226031</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:11]]></Time>
<TimeTick>1608226031</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="91" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:14]]></Time>
<TimeTick>1608226034</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="97" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:18]]></Time>
<TimeTick>1608226038</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="103" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[[ CONTROL ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:19]]></Time>
<TimeTick>1608226039</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="105" >
<Disp><![CDATA[[ CONTROL ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[[ CONTROL ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["97144"]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:20]]></Time>
<TimeTick>1608226040</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="108" >
<Disp><![CDATA[[ CONTROL ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[[ Static ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:23]]></Time>
<TimeTick>1608226043</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="112" >
<Disp><![CDATA[[ Static ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[[ Static ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:27]]></Time>
<TimeTick>1608226047</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="116" >
<Disp><![CDATA[[ Static ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[[ Static ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:30]]></Time>
<TimeTick>1608226050</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="120" >
<Disp><![CDATA[[ Static ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:33]]></Time>
<TimeTick>1608226053</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="126" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:36]]></Time>
<TimeTick>1608226056</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="132" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:39]]></Time>
<TimeTick>1608226059</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="138" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[[ CONTROL ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:42]]></Time>
<TimeTick>1608226062</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="140" >
<Disp><![CDATA[[ CONTROL ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[[ CONTROL ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["SUPP97144"]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:43]]></Time>
<TimeTick>1608226063</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="143" >
<Disp><![CDATA[[ CONTROL ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[[   Save  ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:43]]></Time>
<TimeTick>1608226063</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="145" >
<Disp><![CDATA[[   Save  ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[[   Save  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:45]]></Time>
<TimeTick>1608226065</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="148" >
<Disp><![CDATA[[   Save  ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[[ Supplier Maintenance ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:48]]></Time>
<TimeTick>1608226068</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="150" >
<Disp><![CDATA[[ Supplier Maintenance ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[[ Supplier Maintenance ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:48]]></Time>
<TimeTick>1608226068</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="151" >
<Disp><![CDATA[[ Supplier Maintenance ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[[ Supplier Maintenance ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot create a file when that file already exists.
]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:48]]></Time>
<TimeTick>1608226068</TimeTick>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[[ Supplier Maintenance ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = .*.*<br>Mercury Class = Browser<br>]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:48]]></Time>
<TimeTick>1608226068</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="153" status="Warning" nType="Description" >
<Disp><![CDATA[[ Supplier Maintenance ]]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="152" status="Failed" nType="Run Error" >
<Disp><![CDATA[[ Supplier Maintenance ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[[ OK ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:48]]></Time>
<TimeTick>1608226068</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="155" >
<Disp><![CDATA[[ OK ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[[ OK ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:50]]></Time>
<TimeTick>1608226070</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="158" >
<Disp><![CDATA[[ OK ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[[ Back ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:50]]></Time>
<TimeTick>1608226070</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="160" >
<Disp><![CDATA[[ Back ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[[ Back ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:51]]></Time>
<TimeTick>1608226071</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="163" >
<Disp><![CDATA[[ Back ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="90" status="Failed" >
<Disp><![CDATA[Script Error]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="89" status="Failed" >
<Disp><![CDATA[Script Error]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="88" status="Failed" >
<Disp><![CDATA[OWin_NewSupplier_Wizard]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="63" status="Failed" >
<Disp><![CDATA[OBrwsr_SupplierMaintenance]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[OBrwsr_HQNetMainMenu]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:53]]></Time>
<TimeTick>1608226073</TimeTick>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[OPge_HQNetMainMenu]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:53]]></Time>
<TimeTick>1608226073</TimeTick>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[OPge_HQNetMainMenu.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:53]]></Time>
<TimeTick>1608226073</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="167" >
<Disp><![CDATA[OPge_HQNetMainMenu.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[OwElm_LogOut.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:54]]></Time>
<TimeTick>1608226074</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="170" >
<Disp><![CDATA[OwElm_LogOut.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[[ H.Q.Net Main Menu ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:57:54]]></Time>
<TimeTick>1608226074</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="171" >
<Disp><![CDATA[[ H.Q.Net Main Menu ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[OWEdt_ModuleSearch.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:58:24]]></Time>
<TimeTick>1608226104</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="173" >
<Disp><![CDATA[OWEdt_ModuleSearch.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[OWEdt_ModuleSearch.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[17-12-2020 - 22:58:25]]></Time>
<TimeTick>1608226105</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="176" >
<Disp><![CDATA[OWEdt_ModuleSearch.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[OWEdt_ModuleSearch.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:58:25]]></Time>
<TimeTick>1608226105</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="178" >
<Disp><![CDATA[OWEdt_ModuleSearch.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[OWEdt_ModuleSearch.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Variety Maintenance"]]></Details>
<Time><![CDATA[17-12-2020 - 22:58:26]]></Time>
<TimeTick>1608226106</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="181" >
<Disp><![CDATA[OWEdt_ModuleSearch.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">
<Obj plainTxt="False" ><![CDATA[OWBtn_Go.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:58:27]]></Time>
<TimeTick>1608226107</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="183" >
<Disp><![CDATA[OWBtn_Go.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T76">
<Obj plainTxt="False" ><![CDATA[OWBtn_Go.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[17-12-2020 - 22:58:28]]></Time>
<TimeTick>1608226108</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="186" >
<Disp><![CDATA[OWBtn_Go.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T77">
<Obj plainTxt="False" ><![CDATA[OFr_CFrame]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[17-12-2020 - 22:58:29]]></Time>
<TimeTick>1608226109</TimeTick>
<Step rID="T78">
<Obj plainTxt="False" ><![CDATA[OWElm_VarietyMaintenance.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[17-12-2020 - 22:58:29]]></Time>
<TimeTick>1608226109</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="189" >